name: CI

on:
  push:
    paths-ignore:
    - '**/*.md'
    - 'etc/*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    timeout-minutes: 3
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs-version:
          - "26.1"
          - "26.3"
          - "27.1"
          - "27.2"
          - "28.1"
          - "28.2"
          - "29.1"
          - snapshot
        include:
          - emacs_version: snapshot
            allow_failure: true
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'x64'
    - uses: jcs090218/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'
    - uses: actions/checkout@v4
    - name: Run tests
      if: matrix.allow_failure != true
      run: 'make .eask test'
    - name: Run tests (allow failure)
      if: matrix.allow_failure == true
      run: 'make .eask test || true'
